#!/bin/bash
#oc create secret generic mongodb-project-credentials -n mongo-test \
#--from-literal="user=kyphbebw" \
#--from-literal="publicApiKey=cc04fe07-cf9b-4fbd-a68f-3517f343e67a"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-project-credentials
  namespace: mongo-test
type: Opaque
stringData:
  user: kyphbebw
  publicApiKey: cc04fe07-cf9b-4fbd-a68f-3517f343e67a
